### ISSUE TITLE
Failing almost all tests?

### ISSUE THREAD

**Issue by vtomole** [WeMeetAgain/cl-ipfs-api#5]
Tried to test with (asdf:test-system :cl-ipfs-api), only passed 2 tests out of 30.
Here is my output:
https://ipfs.io/ipfs/QmVpV2y1H34v5B5RR4hHbeXks2kw4tDhsb679WBAafSgFr

**Comment by wemeetagain** [comment]
Yeah, this project hasn't gotten much love in a while...
Try recompiling the newest changes, (though I'm still getting 4 of 30 tests failed.)
Many of the API calls are working, though, some of the more useful ones are not. :cry:
Most notably currently broken is: `add`, `block-put`, all of the api calls that upload data...
I'll try to find time soon to fix these up.

**Comment by vtomole** [comment]
If you need my help, just ask.

**Comment by wemeetagain** [comment]
I'd love some help! Any and all contributions welcome!
